import { GLOBAL_STORES } from "../../constants";

const BASE_PATH = `${GLOBAL_STORES.CHICAGO_ART_INSTITUTE}`;

export const UPDATE_ARTWORKS = `${BASE_PATH}/UPDATE_ARTWORKS`;
export const SET_SEARCH_QUERY = `${BASE_PATH}/SET_SEARCH_QUERY`;
export const SET_PAGINATION = `${BASE_PATH}/SET_PAGINATION`;
export const SET_CONFIG = `${BASE_PATH}/SET_CONFIG`;
export const UPDATE_FILTER_ARTWORK_TYPES = `${BASE_PATH}/UPDATE_FILTER_ARTWORK_TYPES`;
